export type KeyCodeMapping = {
  scanCode: number;
  keyCode: string;
  domCode: string | undefined;
};

export const keyCodeMappings: ReadonlyArray<KeyCodeMapping> = [
  { scanCode: 0x0001, keyCode: "VC_ESCAPE", domCode: "Escape" },
  { scanCode: 0x003b, keyCode: "VC_F1", domCode: "F1" },
  { scanCode: 0x003c, keyCode: "VC_F2", domCode: "F2" },
  { scanCode: 0x003d, keyCode: "VC_F3", domCode: "F3" },
  { scanCode: 0x003e, keyCode: "VC_F4", domCode: "F4" },
  { scanCode: 0x003f, keyCode: "VC_F5", domCode: "F5" },
  { scanCode: 0x0040, keyCode: "VC_F6", domCode: "F6" },
  { scanCode: 0x0041, keyCode: "VC_F7", domCode: "F7" },
  { scanCode: 0x0042, keyCode: "VC_F8", domCode: "F8" },
  { scanCode: 0x0043, keyCode: "VC_F9", domCode: "F9" },
  { scanCode: 0x0044, keyCode: "VC_F10", domCode: "F10" },
  { scanCode: 0x0057, keyCode: "VC_F11", domCode: "F11" },
  { scanCode: 0x0058, keyCode: "VC_F12", domCode: "F12" },
  { scanCode: 0x005b, keyCode: "VC_F13", domCode: "F13" },
  { scanCode: 0x005c, keyCode: "VC_F14", domCode: "F14" },
  { scanCode: 0x005d, keyCode: "VC_F15", domCode: "F15" },
  { scanCode: 0x0063, keyCode: "VC_F16", domCode: "F16" },
  { scanCode: 0x0064, keyCode: "VC_F17", domCode: "F17" },
  { scanCode: 0x0065, keyCode: "VC_F18", domCode: "F18" },
  { scanCode: 0x0066, keyCode: "VC_F19", domCode: "F19" },
  { scanCode: 0x0067, keyCode: "VC_F20", domCode: "F20" },
  { scanCode: 0x0068, keyCode: "VC_F21", domCode: "F21" },
  { scanCode: 0x0069, keyCode: "VC_F22", domCode: "F22" },
  { scanCode: 0x006a, keyCode: "VC_F23", domCode: "F23" },
  { scanCode: 0x006b, keyCode: "VC_F24", domCode: "F24" },
  { scanCode: 0x0029, keyCode: "VC_BACKQUOTE", domCode: "Backquote" },
  { scanCode: 0x0002, keyCode: "VC_1", domCode: "Digit1" },
  { scanCode: 0x0003, keyCode: "VC_2", domCode: "Digit2" },
  { scanCode: 0x0004, keyCode: "VC_3", domCode: "Digit3" },
  { scanCode: 0x0005, keyCode: "VC_4", domCode: "Digit4" },
  { scanCode: 0x0006, keyCode: "VC_5", domCode: "Digit5" },
  { scanCode: 0x0007, keyCode: "VC_6", domCode: "Digit6" },
  { scanCode: 0x0008, keyCode: "VC_7", domCode: "Digit7" },
  { scanCode: 0x0009, keyCode: "VC_8", domCode: "Digit8" },
  { scanCode: 0x000a, keyCode: "VC_9", domCode: "Digit9" },
  { scanCode: 0x000b, keyCode: "VC_0", domCode: "Digit0" },
  { scanCode: 0x000c, keyCode: "VC_MINUS", domCode: "Minus" },
  { scanCode: 0x000d, keyCode: "VC_EQUALS", domCode: "Equal" },
  { scanCode: 0x000e, keyCode: "VC_BACKSPACE", domCode: "Backspace" },
  { scanCode: 0x000f, keyCode: "VC_TAB", domCode: "Tab" },
  { scanCode: 0x003a, keyCode: "VC_CAPS_LOCK", domCode: "CapsLock" },
  { scanCode: 0x001e, keyCode: "VC_A", domCode: "KeyA" },
  { scanCode: 0x0030, keyCode: "VC_B", domCode: "KeyB" },
  { scanCode: 0x002e, keyCode: "VC_C", domCode: "KeyC" },
  { scanCode: 0x0020, keyCode: "VC_D", domCode: "KeyD" },
  { scanCode: 0x0012, keyCode: "VC_E", domCode: "KeyE" },
  { scanCode: 0x0021, keyCode: "VC_F", domCode: "KeyF" },
  { scanCode: 0x0022, keyCode: "VC_G", domCode: "KeyG" },
  { scanCode: 0x0023, keyCode: "VC_H", domCode: "KeyH" },
  { scanCode: 0x0017, keyCode: "VC_I", domCode: "KeyI" },
  { scanCode: 0x0024, keyCode: "VC_J", domCode: "KeyJ" },
  { scanCode: 0x0025, keyCode: "VC_K", domCode: "KeyK" },
  { scanCode: 0x0026, keyCode: "VC_L", domCode: "KeyL" },
  { scanCode: 0x0032, keyCode: "VC_M", domCode: "KeyM" },
  { scanCode: 0x0031, keyCode: "VC_N", domCode: "KeyN" },
  { scanCode: 0x0018, keyCode: "VC_O", domCode: "KeyO" },
  { scanCode: 0x0019, keyCode: "VC_P", domCode: "KeyP" },
  { scanCode: 0x0010, keyCode: "VC_Q", domCode: "KeyQ" },
  { scanCode: 0x0013, keyCode: "VC_R", domCode: "KeyR" },
  { scanCode: 0x001f, keyCode: "VC_S", domCode: "KeyS" },
  { scanCode: 0x0014, keyCode: "VC_T", domCode: "KeyT" },
  { scanCode: 0x0016, keyCode: "VC_U", domCode: "KeyU" },
  { scanCode: 0x002f, keyCode: "VC_V", domCode: "KeyV" },
  { scanCode: 0x0011, keyCode: "VC_W", domCode: "KeyW" },
  { scanCode: 0x002d, keyCode: "VC_X", domCode: "KeyX" },
  { scanCode: 0x0015, keyCode: "VC_Y", domCode: "KeyY" },
  { scanCode: 0x002c, keyCode: "VC_Z", domCode: "KeyZ" },
  { scanCode: 0x001a, keyCode: "VC_OPEN_BRACKET", domCode: "BracketRight" },
  { scanCode: 0x001b, keyCode: "VC_CLOSE_BRACKET", domCode: "BracketLeft" },
  { scanCode: 0x002b, keyCode: "VC_BACK_SLASH", domCode: "Backslash" },
  { scanCode: 0x0027, keyCode: "VC_SEMICOLON", domCode: "Semicolon" },
  { scanCode: 0x0028, keyCode: "VC_QUOTE", domCode: "Quote" },
  { scanCode: 0x001c, keyCode: "VC_ENTER", domCode: "Enter" },
  { scanCode: 0x0033, keyCode: "VC_COMMA", domCode: "Comma" },
  { scanCode: 0x0034, keyCode: "VC_PERIOD", domCode: "Period" },
  { scanCode: 0x0035, keyCode: "VC_SLASH", domCode: "Slash" },
  { scanCode: 0x0039, keyCode: "VC_SPACE", domCode: "Space" },
  { scanCode: 0x0e37, keyCode: "VC_PRINTSCREEN", domCode: "PrintScreen" },
  { scanCode: 0x0046, keyCode: "VC_SCROLL_LOCK", domCode: "ScrolLock" },
  { scanCode: 0x0e45, keyCode: "VC_PAUSE", domCode: "Pause" },
  { scanCode: 0x0e46, keyCode: "VC_LESSER_GREATER", domCode: "IntlBackslash" },
  { scanCode: 0x0e52, keyCode: "VC_INSERT", domCode: "Insert" },
  { scanCode: 0x0e53, keyCode: "VC_DELETE", domCode: "Delete" },
  { scanCode: 0x0e47, keyCode: "VC_HOME", domCode: "Home" },
  { scanCode: 0x0e4f, keyCode: "VC_END", domCode: "End" },
  { scanCode: 0x0e49, keyCode: "VC_PAGE_UP", domCode: "PageUp" },
  { scanCode: 0x0e51, keyCode: "VC_PAGE_DOWN", domCode: "PageDown" },
  { scanCode: 0xe048, keyCode: "VC_UP", domCode: "ArrowUp" },
  { scanCode: 0xe04b, keyCode: "VC_LEFT", domCode: "ArrowLeft" },
  { scanCode: 0xe04c, keyCode: "VC_CLEAR", domCode: "Clear" },
  { scanCode: 0xe04d, keyCode: "VC_RIGHT", domCode: "ArrowRight" },
  { scanCode: 0xe050, keyCode: "VC_DOWN", domCode: "ArrowDown" },
  { scanCode: 0x0045, keyCode: "VC_NUM_LOCK", domCode: "NumLock" },
  { scanCode: 0x0e35, keyCode: "VC_KP_DIVIDE", domCode: "NumpadSubtract" },
  { scanCode: 0x0037, keyCode: "VC_KP_MULTIPLY", domCode: "NumpadMultiply" },
  { scanCode: 0x004a, keyCode: "VC_KP_SUBTRACT", domCode: "NumpadSubtract" },
  { scanCode: 0x0e0d, keyCode: "VC_KP_EQUALS", domCode: "NumpadEquals" },
  { scanCode: 0x004e, keyCode: "VC_KP_ADD", domCode: "NumpadAdd" },
  { scanCode: 0x0e1c, keyCode: "VC_KP_ENTER", domCode: "NumpadEnter" },
  { scanCode: 0x0053, keyCode: "VC_KP_SEPARATOR", domCode: "NumpadDecimal" },
  { scanCode: 0x004f, keyCode: "VC_KP_1", domCode: "Numpad1" },
  { scanCode: 0x0050, keyCode: "VC_KP_2", domCode: "Numpad2" },
  { scanCode: 0x0051, keyCode: "VC_KP_3", domCode: "Numpad3" },
  { scanCode: 0x004b, keyCode: "VC_KP_4", domCode: "Numpad4" },
  { scanCode: 0x004c, keyCode: "VC_KP_5", domCode: "Numpad5" },
  { scanCode: 0x004d, keyCode: "VC_KP_6", domCode: "Numpad6" },
  { scanCode: 0x0047, keyCode: "VC_KP_7", domCode: "Numpad7" },
  { scanCode: 0x0048, keyCode: "VC_KP_8", domCode: "Numpad8" },
  { scanCode: 0x0049, keyCode: "VC_KP_9", domCode: "Numpad9" },
  { scanCode: 0x0052, keyCode: "VC_KP_0", domCode: "Numpad0" },
  { scanCode: 0xee4f, keyCode: "VC_KP_END", domCode: "NumpadEnd" },
  { scanCode: 0xee50, keyCode: "VC_KP_DOWN", domCode: "NumpadArrowDown" },
  { scanCode: 0xee51, keyCode: "VC_KP_PAGE_DOWN", domCode: "NumpadPageDown" },
  { scanCode: 0xee4b, keyCode: "VC_KP_LEFT", domCode: "NumpadArrowLeft" },
  { scanCode: 0xee4c, keyCode: "VC_KP_CLEAR", domCode: "NumpadClear" },
  { scanCode: 0xee4d, keyCode: "VC_KP_RIGHT", domCode: "NumpadArrowRight" },
  { scanCode: 0xee47, keyCode: "VC_KP_HOME", domCode: "NumpadHome" },
  { scanCode: 0xee48, keyCode: "VC_KP_UP", domCode: "NumpadArrowUp" },
  { scanCode: 0xee49, keyCode: "VC_KP_PAGE_UP", domCode: "NumpadPageUp" },
  { scanCode: 0xee52, keyCode: "VC_KP_INSERT", domCode: "NumpadInsert" },
  { scanCode: 0xee53, keyCode: "VC_KP_DELETE", domCode: "NumpadDelete" },
  { scanCode: 0x002a, keyCode: "VC_SHIFT_L", domCode: "ShiftLeft" },
  { scanCode: 0x0036, keyCode: "VC_SHIFT_R", domCode: "ShiftRight" },
  { scanCode: 0x001d, keyCode: "VC_CONTROL_L", domCode: "ControlLeft" },
  { scanCode: 0x0e1d, keyCode: "VC_CONTROL_R", domCode: "ControlRight" },
  { scanCode: 0x0038, keyCode: "VC_ALT_L", domCode: "AltLeft" },
  { scanCode: 0x0e38, keyCode: "VC_ALT_R", domCode: "AltRight" },
  { scanCode: 0x0e5b, keyCode: "VC_META_L", domCode: "MetaLeft" },
  { scanCode: 0x0e5c, keyCode: "VC_META_R", domCode: "MetaRight" },
  { scanCode: 0x0e5d, keyCode: "VC_CONTEXT_MENU", domCode: "ContextMenu" },
  { scanCode: 0xe05e, keyCode: "VC_POWER", domCode: "Power" },
  { scanCode: 0xe05f, keyCode: "VC_SLEEP", domCode: "Sleep" },
  { scanCode: 0xe063, keyCode: "VC_WAKE", domCode: "WakeUp" },
  { scanCode: 0xe022, keyCode: "VC_MEDIA_PLAY", domCode: "MediaPlayPause" },
  { scanCode: 0xe024, keyCode: "VC_MEDIA_STOP", domCode: "MediaStop" },
  { scanCode: 0xe010, keyCode: "VC_MEDIA_PREVIOUS", domCode: "MediaTrackPrevious" },
  { scanCode: 0xe019, keyCode: "VC_MEDIA_NEXT", domCode: "MediaTrackNext" },
  { scanCode: 0xe06d, keyCode: "VC_MEDIA_SELECT", domCode: "MediaSelect" },
  { scanCode: 0xe02c, keyCode: "VC_MEDIA_EJECT", domCode: "Eject" },
  { scanCode: 0xe020, keyCode: "VC_VOLUME_MUTE", domCode: "AudioVolumeMute" },
  { scanCode: 0xe030, keyCode: "VC_VOLUME_UP", domCode: "AudioVolumeUp" },
  { scanCode: 0xe02e, keyCode: "VC_VOLUME_DOWN", domCode: "AudioVolumeDown" },
  { scanCode: 0xe06c, keyCode: "VC_APP_MAIL", domCode: "LaunchMail" },
  { scanCode: 0xe021, keyCode: "VC_APP_CALCULATOR", domCode: "LaunchApp2" },
  { scanCode: 0xe03c, keyCode: "VC_APP_MUSIC", domCode: undefined },
  { scanCode: 0xe064, keyCode: "VC_APP_PICTURES", domCode: undefined },
  { scanCode: 0xe065, keyCode: "VC_BROWSER_SEARCH", domCode: "BrowserSearch" },
  { scanCode: 0xe032, keyCode: "VC_BROWSER_HOME", domCode: "BrowserHome" },
  { scanCode: 0xe06a, keyCode: "VC_BROWSER_BACK", domCode: "BrowserBack" },
  { scanCode: 0xe069, keyCode: "VC_BROWSER_FORWARD", domCode: "BrowserForward" },
  { scanCode: 0xe068, keyCode: "VC_BROWSER_STOP", domCode: "BrowserStop" },
  { scanCode: 0xe067, keyCode: "VC_BROWSER_REFRESH", domCode: "BrowserRefresh" },
  { scanCode: 0xe066, keyCode: "VC_BROWSER_FAVORITES", domCode: "BrowserFavorites" },
  { scanCode: 0x0070, keyCode: "VC_KATAKANA", domCode: "KanaMode" },
  { scanCode: 0x0073, keyCode: "VC_UNDERSCORE", domCode: "IntlRo" },
  { scanCode: 0x0077, keyCode: "VC_FURIGANA", domCode: "Lang4" },
  { scanCode: 0x0079, keyCode: "VC_KANJI", domCode: "Convert" },
  { scanCode: 0x007b, keyCode: "VC_HIRAGANA", domCode: "NonConvert" },
  { scanCode: 0x007d, keyCode: "VC_YEN", domCode: "IntlYen" },
  { scanCode: 0x007e, keyCode: "VC_KP_COMMA", domCode: "NumpadComma" },
  { scanCode: 0xff75, keyCode: "VC_SUN_HELP", domCode: undefined },
  { scanCode: 0xff78, keyCode: "VC_SUN_STOP", domCode: undefined },
  { scanCode: 0xff76, keyCode: "VC_SUN_PROPS", domCode: undefined },
  { scanCode: 0xff77, keyCode: "VC_SUN_FRONT", domCode: undefined },
  { scanCode: 0xff74, keyCode: "VC_SUN_OPEN", domCode: undefined },
  { scanCode: 0xff7e, keyCode: "VC_SUN_FIND", domCode: undefined },
  { scanCode: 0xff79, keyCode: "VC_SUN_AGAIN", domCode: undefined },
  { scanCode: 0xff7a, keyCode: "VC_SUN_UNDO", domCode: undefined },
  { scanCode: 0xff7c, keyCode: "VC_SUN_COPY", domCode: undefined },
  { scanCode: 0xff7d, keyCode: "VC_SUN_INSERT", domCode: undefined },
  { scanCode: 0xff7b, keyCode: "VC_SUN_CUT", domCode: undefined },
  { scanCode: 0x0000, keyCode: "VC_UNDEFINED", domCode: undefined },
] as const;

const domCodeToScanCodeMap = new Map<string, number>();
const scanCodeToKeyCodeMap = new Map<number, string>();
keyCodeMappings.forEach(({ scanCode, keyCode, domCode }) => {
  if (domCode) {
    domCodeToScanCodeMap.set(domCode, scanCode);
  }

  scanCodeToKeyCodeMap.set(scanCode, keyCode);
});

export const mapDomEventToScanCode = (ev: KeyboardEvent): number => {
  const code = domCodeToScanCodeMap.get(ev.code);
  return code || 0;
};

export const scanCodeToKeyCode = (scanCode: number): string => {
  return scanCodeToKeyCodeMap.get(scanCode) || "VC_UNKNOWN";
};
